### ISSUE TITLE
[Maintainer Request] Let me translate to german

### ISSUE THREAD

**Issue by legalmat** [social-manager-tools/socialmanagertools-docs#76]
### What language you want introduce? 

German
### Who are you? 

Andre Lisbert, am Using Open Source for over 16 years and always had the goal to support any cool thang and give back. 
### Explain motivation

Well, first, it's amazing that someone has the ability and the energy to create what you created and maintain it even (cause open source lives, will survive and persists and even leads ONLY through maintenance, and in times like this, I want to start actively making a difference, as a clear mind and person who sees. As well, the knowledge about RPA and bot software leads back to the year 2004 when the whole thing was more a niche, only to become so huge as today. The same is for codeless and no programming. Cheers, in hope to start together with you. Earliest start is realistically the 15th of June.
All the best. 
Andre

**Comment by ptkdev** [comment]
You are welcome, send pull request with new translations and add your name to credits in main README.md and package.json

**Comment by legalmat** [comment]
Hi, thanks, just as I ve said, it will be realistic from 15th of
      June on.
    
    On 30.05.20 16:43, Patryk Rzucidło
      wrote:
    
    
      
      You are welcome, send pull request with new translations and
        add your name to credits in main README.md and package.json
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/social-manager-tools/socialmanagertools-docs/issues/76#issuecomment-636340275",
"url": "https://github.com/social-manager-tools/socialmanagertools-docs/issues/76#issuecomment-636340275",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
    
    -- 
Mit freundlichen Grüßen

Andre Lisbert
Allensteiner Str. 4
53340 Meckenheim

Tel.: +49 - 2225 - 951 8850
Mobil 1: +49 - 176 - 1018 7870
Fax: +49 - 2225 – 951 8849
